# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=64, verbose_name='размер')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='newspaper')),
                ('prices', models.TextField(blank=True, verbose_name='цены')),
                ('discounts', models.TextField(blank=True, verbose_name='скидки')),
                ('price_list', models.ImageField(blank=True, upload_to='price_list', verbose_name='прайс-лист')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Newspaper'),
        ),
    ]
