# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='is_website',
            field=models.BooleanField(default=False, verbose_name='сайт'),
        ),
    ]
